Ajout d'exercices pour les GRASP
fuhrmanator/log210-ndc-quarto pull request #105
Opened 2023-02-14 20:51 UTC by Olon11

Travail en cours. Ne pas fusionner tout de suite.

2023-02-15 18:39 UTC, fuhrmanator commented
C'est bien. Malheureusement, quarto ne supporte pas ton idée de `#sol-`, c'est `::: {.solution}` comme expliqué ici: https://quarto.org/docs/authoring/cross-references.html#theorems-and-proofs.

Au fait, j'aime mieux mettre la solution juste après l'exercice, mais en bloc masqué (ça ne marche que sur HTML):

```md
:::: {.callout-note collapse="true"}

(solution est ici)...
:::: 
```

Je vais faire un commit sur ton PR qui modifie ça.

2023-02-15 18:45 UTC, Olon11 commented
> Malheureusement, quarto ne supporte pas ton idée de #sol-...

Oui, j'ai vu cela. Je pensais que c'était un style que tu avais créé. Je voulais traiter cela plus tard.

> Au fait, j'aime mieux mettre la solution juste après l'exercice
> Je vais faire un commit sur ton PR qui modifie ça.

Ok!

2023-02-15 18:48 UTC, fuhrmanator commented
En HTML ça donne: 

![image](https://user-images.githubusercontent.com/7606540/219123752-ff6d611c-9de6-41cf-bbb1-c477aba7307b.png)


En PDF ça donne:

![image](https://user-images.githubusercontent.com/7606540/219123192-ed529730-6a39-4ee9-a977-91b0f9e27ca3.png)

2023-02-15 18:59 UTC, fuhrmanator requested changes

2023-02-15 18:59 UTC, fuhrmanator commented on GRASP.qmd
>  Puisque la classe `Circle` possède les informations nécessaires (`radius`) pour calculer `area`, `diameter` et `perimeter`, c'est elle qui doit contenir les méthodes pour calculer ces propriétés. Cel
On dit plutôt `circumference` en anglais pour un cercle.

2023-02-15 18:59 UTC, fuhrmanator commented on GRASP.qmd
>  Puisque la classe `Circle` possède les informations nécessaires (`radius`) pour calculer `area`, `diameter` et `perimeter`, c'est elle qui doit contenir les méthodes pour calculer ces propriétés. Cel
> Cela augmente la cohésion de la classe `SomeClass`

puisqu'elle a moins de responsabilités

(je commencerais une nouvelle phrase pour la complétude de la classe Circle)

2023-02-15 18:59 UTC, fuhrmanator commented on GRASP.qmd
>  Puisque la classe `Circle` possède les informations nécessaires (`radius`) pour calculer `area`, `diameter` et `perimeter`, c'est elle qui doit contenir les méthodes pour calculer ces propriétés. Cel
Une autre remarque (je ne le fais pas de manière constante). Faire une phrase par ligne dans un texte markdown facilite la vie, car on peut voir mieux les diffs et faire les commentaires dans les reviews. Markdown (comme LaTeX) ne crée pas un nouveau paragraphe s'il n'y a pas de ligne vide entre deux phrases.

2023-02-15 18:59 UTC, fuhrmanator commented on GRASP.qmd
> +        const perimeter = Math.PI * c.radius * 2;
circumference

2023-02-15 18:59 UTC, fuhrmanator commented on GRASP.qmd
> +Appliquez le GRASP Expert en information pour le code suivant:
pour améliorer la conception des classes dans le code suivant

2023-02-17 18:55 UTC, fuhrmanator approved these changes

2023-02-17 18:56 UTC, fuhrmanator commented
Je merge @Olon11 ?

2023-02-17 19:16 UTC, Olon11 commented
Oui, si tu veux ajouter l'exercice tout de suite au dépôt. Je vais proposer d'autres exercices dans une autre branche.

2023-02-17 19:45 UTC, merged