Expliqué que les associations ne doivent pas être représentées par des attributs
fuhrmanator/log210-ndc-quarto pull request #116
Opened 2023-08-19 01:02 UTC by Olon11

#114

2023-08-19 01:02 UTC, Olon11 commented
J'ai ajouté une explication simple. Est-ce que ça correspond à ce que tu voulais?

2024-01-26 18:00 UTC, fuhrmanator requested changes

2024-01-26 18:01 UTC, fuhrmanator commented on MDD.qmd
> +Contrairement aux associations des diagrammes de classes logicielles, ce ne sont pas toutes les associations conceptuelles que seront implémentées dans le logiciel.
Désolé pour le retard - je n'avais pas "soumis" la révision

2024-01-28 00:01 UTC, Olon11 commented on MDD.qmd
> +Contrairement aux associations des diagrammes de classes logicielles, ce ne sont pas toutes les associations conceptuelles que seront implémentées dans le logiciel.
C'est effectivement « qui seront implémentées ».

2024-01-29 02:58 UTC, fuhrmanator approved these changes

2024-01-29 02:59 UTC, merged