Mise à jour de Besoins.qmd pour l'ajout de la norme ISO 25010:2023
fuhrmanator/log210-ndc-quarto pull request #125
Opened 2024-04-29 19:57 UTC by probitaille

Ajout de la norme ISO 25010:2023 dans le chapitre 2 du manuel.

2024-05-09 14:10 UTC, fuhrmanator requested changes
STP faire un contrôle de l'orthographe

2024-05-09 14:10 UTC, fuhrmanator commented on Besoins.qmd
> +Bien que le modèle FURPS+ proposé en 1992 puisse être encore utilisé aujourd'hui, il existe dorénavant une suite de normes publié par l'Organisation internationale de normalisation (ISO) afin de four
Je crois qu'il faut contrôler le français -- "suite de normes publié" a des problèmes d'accord. ChatGPT peut t'aider. 

"la suite" ... "connu sont le nom" est une faute d'accord et de frappe je crois?

2024-05-09 14:10 UTC, fuhrmanator commented on Besoins.qmd
> +  - **Intégration sécurisée** (*Safe integration*). C'est la mesure de la capacité d'un logiciel à maintenir la sécurité pendant et après son intégration avec un ou plusieurs composants, tels que des
Je n'ai plus la license Antidote, mais je sais qu'il y a des fautes d'orthographe dans tout ce texte. ChatGPT peut aider à corriger les problèmes.

2024-05-13 14:02 UTC, probitaille commented on Besoins.qmd
> +  - **Intégration sécurisée** (*Safe integration*). C'est la mesure de la capacité d'un logiciel à maintenir la sécurité pendant et après son intégration avec un ou plusieurs composants, tels que des
Je viens de corriger le texte avec Antidote. Il y avait effectivement quelques fautes et un mot erroné.

2024-05-15 01:57 UTC, fuhrmanator approved these changes

2024-05-15 01:57 UTC, merged